version: '3.6'
services:
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev

        ports:
            - '7800:3000'
        volumes:
            - /app/node_modules
            - .:/app
